### PR TITLE
Swift 3 support

### PR DESCRIPTION
**Pull request by lucianomarisi**
Includes API changes and support for decoding keypaths

### CODE REVIEW

**Comment by yonaskolb** [comment]
Adding support keyPath is great! What if a property has a "." in it though?

**Comment by lucianomarisi** [comment]
@yonaskolb I discussed this idea while developing the keypath feature with work colleagues and the argument was to prefer a cleaner and simpler API, i.e. just `json(atKeyPath:)` instead of having 2 `json(atKeyPath:)` and `json(atKey:)` where the latter one is only useful for keys with dots. None of us have ever worked with a backend service that had dots in their keys so maybe we did not foresee something.

Has this changed introduced issues in your project(s) and is it stopping your from using the 3.0.0 version of the library or is your concern a theoretical one. If it's an issue we can figure out the best way to cover the edgecase where the key has a `.` otherwise I can add this as a note in the README.

**Comment by lucianomarisi** [comment]
@yonaskolb I had a another conversation with a colleague and his suggestion was to be able to escape dots, for example the developer would specify `"some\.word"` for the key `some.word`

**Comment by yonaskolb** [comment]
It was mostly a theoretical limitation, though I have seen it out in the wild. I agree that simplicity should trump here. 
I do think some workaround is needed though, and I think the escaping solution is a great one. Though in that specific example you would also need to escape the actual slash to be able to compile in swift `"some\\.word"`

**Comment by lucianomarisi** [comment]
I'll create an issue in that case since at the moment I don't have time to fix this.

**Pull request merged**
