### PR TITLE
Swift 5 infinite loop - fix optionals

### PR DESCRIPTION
**Pull request by Jon889**
As explained in this issue, this PR removes the optional methods

https://github.com/lucianomarisi/JSONUtilities/issues/31

Either this PR or #32 should be merged, not both

### CODE REVIEW

**Comment by lucianomarisi** [comment]
@Jon889 I'd prefer this approach as opposed to #32, are you happy for me to merge it? 

By the way really cool that you provided code for both approaches!

**Comment by Jon889** [comment]
Yep, happy with either way, just we might need to keep an eye on it init the future as it’s not recommended to overload based throwing or not. 

Np, just trying to make it as easy as possible :)

**Comment by Jon889** [comment]
Thanks for merging it :) can you deploy it as well? 
(I’m happy to do the boring stuff if you want to add me as a collaborator, don’t worry I wouldn’t make changes without your input/approval, completely understand if you don’t want to though! :))

**Comment by lucianomarisi** [comment]
I've added you as collaborator to the project, so you should be able to merge new stuff in the future.

**Comment by Jon889** [comment]
Awesome thanks! Also just in general, thanks for making this framework, it's been really useful and the API using generics and throwing errors is much better than say SwiftyJSON.

**Pull request merged**
