### PR TITLE
Invalid Item Notifier

### LINKED ISSUE #18: Ability to listen to InvalidItemBehaviour
It would great to somehow hook into when InvalidItemBehaviours happen, especially the non throwing kinds, like `.remove` `.value`, and `.custom` when it doesn't throw.
That way a client app can log a warning or somehow be alerted to otherwise unnoticed events. (To for example alert the backend that certain elements are malformed)

Because there is no state that is passed through the decoding process, maybe just a static func on InvalidItemNotifier that would maintain a static array of listeners: 
`static func addListener(handler: (InvalidItemEvent) -> ()) -> InvalidItemNotifier.Listener`

Thoughts?

### PR DESCRIPTION
**Pull request by yonaskolb**
Fixes #18

### CODE REVIEW

**Comment by yonaskolb** [comment]
rebased off master

**Comment by yonaskolb** [comment]
Rebased off master

**Comment by yonaskolb** [comment]
So based off the discussion in #18, does that mean that this probably won't get merged in?

**Comment by lucianomarisi** [comment]
The truth is that I haven't had time to properly look into this idea. Since it's a big change that we'll need to support in future versions I want to make sure it's the best approach we can think of, so I kept the PR opened for now until I have time to think about it.

**Pull request closed without merging**
